idist: bionic
sudo: enabled
#language: c++, python
language: generic
#c++:
#  - "c++14"
python:
  - "3.6"

env:
  global:
    - ROS2_WS_DIAGNOSTICS=~/ros2_ws_diagnostics
    - ROS2_WS_DIAGNOSTICS_SRC=${ROS2_WS_DIAGNOSTICS}/src

# command to install dependencies
install:
  - sudo apt update && sudo apt install curl gnupg2
  - curl http://repo.ros2.org/repos.key | sudo apt-key add -
  - mkdir -p ~/ros2_ws/src
  - sudo apt install -y  python3-vcstool  
  - cd ~/ros2_ws
  - wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
  - vcs import src < ros2.repos
  - export ROS_DISTRO=bouncy
  - sudo apt update && sudo apt install -y python3-rosdep ros-$ROS_DISTRO-ros-base
  - sudo apt install python3-argcomplete
  - sudo apt install python3-colcon-common-extensions
  - sudo apt install build-essential
  - source ~/ros2_ws/install/setup.bash
  - sudo rosdep init
  - rosdep update
  - sudo apt install python3-pip
  - sudo pip3 install argcomplete setuptools pytest pep257 flake8
  - sudo -H python3 -m pip install -U setuptools

    
# command to run tests
script:
  - mkdir -p $ROS2_WS_DIAGNOSTICS
  - mkdir -p $ROS2_WS_DIAGNOSTICS_SRC
  - ln -s $TRAVIS_BUILD_DIR $ROS2_WS_DIAGNOSTICS_SRC
  - cd $ROS2_WS_DIAGNOSTICS
  - colcon build
  - colcon test

branches:
  only:
    - ros2-devel

notifications:
email: false

