diagnostic_aggregator:
        ros__parameters:
                analyzers_params:
                        motors:
                                type: diagnostic_aggregator/GenericAnalyzer
                                path: Motors
                                startswith: 'EtherCAT'
                        computers:
                                type: diagnostic_aggregator/GenericAnalyzer
                                path: Computers
                                contains: [
                                'HD Temp',
                                ' CPU Usage',
                                'CPU Temperature',
                                'HD Usage',
                                '  NFS']
                        joints:
                                type: diagnostic_aggregator/GenericAnalyzer
                                path: Joints
                                startswith: 'Joint'
                        power:
                                type: diagnostic_aggregator/GenericAnalyzer
                                path: 'Power System'
                                timeout: 5.0
                                startswith: [
                                'Smart Battery',
                                'Power board']
                                expected: [
                                'IBPS 1',
                                ' IBPS 2',
                                'IBPS 3',
                                'IBPS 0']
                        sensors:
                                type: diagnostic_aggregator/AnalyzerGroup
                                path: Sensors        
                                analyzers_params:
                                        base_hk:
                                                type: diagnostic_aggregator/GenericAnalyzer
                                                path: Base Hokuyo
                                                timeout: 5.0
                                                find_and_remove_prefix: base_hokuyo_node
                                                num_items: 3
                                                startswith: 'Sensor'
